// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package nl.vu.cs.s2.simbadtest;

import javax.vecmath.Point3d;


/************************************************************/
/**
 * 
 */
public class Coordinate {
	
	public Coordinate(int x, int y) {
		position = new Point3d(x,0,y);
		isObstacle = false;
		isRecorded = false;
	}
	/**
	 * 
	 */
	public Point3d position;
	
	public boolean isObstacle;
	/**
	 * 
	 */
	public boolean isRecorded;
};
