// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package nl.vu.cs.s2.simbadtest;

import javax.vecmath.Point3d;

import nl.vu.cs.s2.simbadtest.Coordinate;

/************************************************************/
/**
 * 
 */
public class Path {
	/**
	 * 
	 */
	Point3d[] stepArray = new Point3d[1000];
	/**
	 * 
	 */
	private int stepCounter = 0;
	/**
	 * 
	 */
	public void addStep(double x, double y) {
		
		stepArray[stepCounter] = new Point3d(x, 0, y);
		stepCounter++;
	}

	/**
	 * 
	 */
	public void reset() {
	}
};
