// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package nl.vu.cs.s2.simbadtest;

import javax.vecmath.Vector3d;

import nl.vu.cs.s2.simbadtest.Rover;
import simbad.sim.EnvironmentDescription;

/************************************************************/
/**
 * 
 */
public class roverFactory {
	/**
	 * 
	 */
	public Rover[] rover;
	
	static int roverNumber;

	roverFactory() {
		roverNumber = 0;
	}
	/**
	 * 
	 * @param type 
	 * @return 
	 */
	public static Rover getRover(int type, controlCentre mainControlCentre, EnvironmentDescription environment) {
		
		if(type == 1) {

			MappingRover mappingRover = new MappingRover(new Vector3d(0,0,0),("MappingRover" + roverNumber), mainControlCentre);
			environment.add(mappingRover);
			System.out.println(mappingRover.name);
			roverNumber++;
			return mappingRover;
		}else {
			
			System.out.println("oioi");
			DataCollectionRover dataCollectionRover = new DataCollectionRover(new Vector3d((-(environment.worldSize/2)+1),0,(-(environment.worldSize/2))+1),"1", mainControlCentre);
			environment.add(dataCollectionRover);
			return dataCollectionRover;
		}
	}
};
