// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package nl.vu.cs.s2.simbadtest;

import nl.vu.cs.s2.simbadtest.DataCollectionRover;
import nl.vu.cs.s2.simbadtest.Environment;

/************************************************************/
/**
 * 
 */
public class Singleton {

	public static Singleton mapInstance;

	
	public static Singleton getInstanceMap() {
		return mapInstance;
	}


};
